language: java
notifications:
  email:
    recipients:
      - ibmttz13.5@gmail.com
      - alzmievskiy@inbox.ru
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always